### PR TITLE
vaapi: ERROR if vaCreateConfig fails

### LINKED ISSUE #443: provide an error message when Profile or Entrypoint are not supported
libyami client should have a meaningful error message displayed when either the Profile or Entrypoint are not supported.  User should realize that the particular generation of hardware doesn't support a Profile or Entrypoint that is going to be used. .

### PR DESCRIPTION
**Pull request by stripes416**
Also correct grammar in nearby error message.

Fixes #443
Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>

### CODE REVIEW

File: vaapi/vaapicontext.cpp [hunk 1]
```diff
@@ -90,14 +90,16 @@ YamiStatus VaapiConfig::create(const DisplayPtr& display,
...
-        ERROR("Unsupport profile");
+        ERROR("Unsupported profile.");
         return YAMI_UNSUPPORTED;
     }
 
     vaStatus = vaCreateConfig(display->getID(), profile, entry, attribList, numAttribs, &config);
 
-    if (!checkVaapiStatus(vaStatus, "vaCreateConfig "))
+    if (!checkVaapiStatus(vaStatus, "vaCreateConfig ")) {
+	ERROR("Unable to create config. This may be due to an unsupported entrypoint.");
```
Comment (chivakker) [inline vaapi/vaapicontext.cpp]: What about saying: "Unable to create config for profile %s and entrypoint %s".  

At this point of execution you know which entrypoint and profile were requested. Then user can run vainfo to confirm the codec is supported.

Comment (xuguangxin) [reply vaapi/vaapicontext.cpp]: maybe we can return YAMI_UNSUPPORTED here too

**Comment by stripes416** [comment]
Sounds good. I'll make those changes.

File: vaapi/vaapicontext.cpp (hunk 1 above)
Comment (stripes416) [reply vaapi/vaapicontext.cpp]: chivakker, I have some questions about how to go about what you requested.

I don't see a good way to converting the profile / entrypoint to a string with libva or libyami. However, libva-utils/vainfo/vainfo.c does contain such code.

I could copy-and-paste the code from vainfo.c into this file or yamiinfo.cpp, but that seems a little distasteful from a maintenance perspective. Alternatively I could move the code to libva/va/va.c and use it from both projects. There's a function with a similar purpose already in va.c: vaErrorStr( ). However, doing so would add another API to libva which we may not want.

What do you think?

Comment (chivakker) [reply vaapi/vaapicontext.cpp]: @stripes416 IIRC, there should be a ProfileToString utility function and EntrypointToString.  I think it might be inside the test folder.  You could probably copy them instead.

Comment (uartie) [reply vaapi/vaapicontext.cpp]: I'd prefer to see C++ style string conversions used... see "toString()" and stream operators from intel-vaapi-driver/test/i965_streamable.h.  It's ok to copy that code into this project (e.g. add "vaapi/vaapistreamable.h").

Comment (uartie) [reply vaapi/vaapicontext.cpp]: @xuguangxin returning YAMI_UNSUPPORTED only makes sense when vaStatus is VA_STATUS_ERROR_UNSUPPORTED_PROFILE or VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT, right?  Otherwise, we should return YAMI_FAIL?

File: vaapi/vaapicontext.cpp [hunk 2]
```diff
@@ -90,14 +90,16 @@ YamiStatus VaapiConfig::create(const DisplayPtr& display,
     VAConfigID config;
 
     if (!checkProfileCompatible(display, profile)){
-        ERROR("Unsupport profile");
+        ERROR("Unsupported profile.");
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: In addition, please print the profile here.

File: vaapi/vaapicontext.cpp (hunk 1 above)
Comment (xuguangxin) [reply vaapi/vaapicontext.cpp]: @uartie , yeah, you are right

**Comment by xuguangxin** [comment]
@stripes416 any update on this?

**Comment by uartie** [comment]
LibVA 2.0 has been merged to master.  This PR needs to be rebased on top of libyami's libva 2.0 compatibility commits... please rebase to fix intel/ci builds.

File: vaapi/vaapicontext.cpp [hunk 3]
```diff
@@ -24,6 +24,7 @@
 #include "common/common_def.h"
 #include "vaapi/vaapidisplay.h"
 #include "vaapi/VaapiUtils.h"
+#include <va/va_str.h>
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: We can't include this unconditionally since libyami supports both libva 1.x and libva 2.0

File: vaapi/vaapicontext.cpp [hunk 4]
```diff
@@ -84,14 +85,17 @@ YamiStatus VaapiConfig::create(const DisplayPtr& display,
     VAConfigID config;
 
     if (!checkProfileCompatible(display, profile)){
-        ERROR("Unsupport profile");
+        ERROR("Unsupported profile: %s.", vaProfileStr(profile));
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: va...Str() methods only available in libva 2.0

File: vaapi/vaapicontext.cpp [hunk 5]
```diff
@@ -84,14 +85,17 @@ YamiStatus VaapiConfig::create(const DisplayPtr& display,
...
         return YAMI_UNSUPPORTED;
     }
 
     vaStatus = vaCreateConfig(display->getID(), profile, entry, attribList, numAttribs, &config);
 
-    if (!checkVaapiStatus(vaStatus, "vaCreateConfig "))
+    if (!checkVaapiStatus(vaStatus, "vaCreateConfig ")) {
+        ERROR("Unable to create config for profile: %s and entrypoint: %s.",
+              vaProfileStr(profile), vaEntrypointStr(entry));
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: same as above

**Review by uartie — CHANGES_REQUESTED** [review]

File: vaapi/vaapicontext.cpp [hunk 6]
```diff
@@ -24,8 +24,10 @@
 #include "common/common_def.h"
 #include "vaapi/vaapidisplay.h"
 #include "vaapi/VaapiUtils.h"
+#include "vaapi/vaapistreamable.h"
 #include <algorithm>
 #include <vector>
+#include <sstream>
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: This is already included indirectly via vaapistreamable.h.  It is not even needed in this unit if you use toString(...) instead (which you just added in vaapistreamable.h).

File: vaapi/vaapicontext.cpp [hunk 7]
```diff
@@ -84,14 +86,21 @@ YamiStatus VaapiConfig::create(const DisplayPtr& display,
     VAConfigID config;
 
     if (!checkProfileCompatible(display, profile)){
-        ERROR("Unsupport profile");
+        std::stringstream msg;
+        msg << "Unsupported profile: " << profile << std::endl;
+        ERROR("%s", msg.str().c_str());
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: `ERROR("Unsupported profile: %s", toString(profile).c_str());` would be simpler.

File: vaapi/vaapicontext.cpp [hunk 8]
```diff
@@ -84,14 +86,21 @@ YamiStatus VaapiConfig::create(const DisplayPtr& display,
...
     }
 
     vaStatus = vaCreateConfig(display->getID(), profile, entry, attribList, numAttribs, &config);
 
-    if (!checkVaapiStatus(vaStatus, "vaCreateConfig "))
+    if (!checkVaapiStatus(vaStatus, "vaCreateConfig ")) {
+        std::stringstream msg;
+        msg << "Unable to create config for profile: " << profile
+            << " and entrypoint: " << entry << std::endl;
+        ERROR("%s", msg.str().c_str());
```
Comment (uartie) [inline vaapi/vaapicontext.cpp]: This is what toString(...) is for... so you don't have to do these extra steps before the logging macros.

File: vaapi/vaapistreamable.h [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+ * of the Software.
+ *
+ * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
+ * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+ * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
+ * IN NO EVENT SHALL INTEL AND/OR ITS SUPPLIERS BE LIABLE FOR
+ * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
+ * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
+ * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+ */
```
Comment (uartie) [inline vaapi/vaapistreamable.h]: Please use the Apache 2.0 license like the other files.

**Review by uartie — CHANGES_REQUESTED** [review]

File: vaapi/vaapicontext.cpp (hunk 8 above)
Comment (uartie) [reply vaapi/vaapicontext.cpp]: Since checkVaapiStatus(vaStatus, "vaCreateConfig") already prints "vaCreateConfig: the requested VAEntryPoint is not supported", perhaps just do:

```
ERROR("   VAProfile: %s", toString(profile).c_str());
ERROR("VAEntrypoint: %s", toString(entry).c_str());
```

...to cut down on the error message redundancy.

Comment (uartie) [reply vaapi/vaapicontext.cpp]: or maybe:

```
ERROR("%s, %s", toString(profile).c_str(), toString(entry).c_str());
```

**Review by uartie — APPROVED** [review]

**Comment by xuguangxin** [comment]
Hi @stripes416 ,
this great! 

thanks all Daniel and U.Artie for review.
