### PR TITLE
Common unittest

### LINKED ISSUE #728: common/unittest with failed case
libyami]$./common/unittest
...................
[  FAILED  ] UtilsTest.guessResolutionOverflow (0 ms)
[ RUN      ] UtilsTest.getPlaneResolution
libyami error 10944 (utils.cpp, 193): do not support this format, fourcc
libyami error 10944 (utils.cpp, 193): do not support this format, fourcc Y800
libyami error 10944 (utils.cpp, 193): do not support this format, fourcc 411P
libyami error 10944 (utils.cpp, 193): do not support this format, fourcc ARGB
[       OK ] UtilsTest.getPlaneResolution (0 ms)
[----------] 4 tests from UtilsTest (0 ms total)

[----------] 1 test from ThreadTest
[ RUN      ] ThreadTest.FullTest
this may take some time
libyami error 10944 (Thread.cpp, 110): : sent job after stop()
[       OK ] ThreadTest.FullTest (10003 ms)
[----------] 1 test from ThreadTest (10003 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 4 test cases ran. (10005 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] NalReaderTest.ReadAsUnits
[  FAILED  ] NalReaderTest.ReadAsWhole
[  FAILED  ] UtilsTest.guessResolutionOverflow

### PR DESCRIPTION
**Pull request by wudping**
There are some error in libyami/common/unittest, this patches will fix them.

to fix #728

### CODE REVIEW

File: common/nalreader_unittest.cpp [hunk 1]
```diff
@@ -53,20 +53,20 @@ const std::array<uint8_t, 39> g_data = {
...
-    NalReader reader(&g_data[0], g_data.size(), false);
+    NalReader reader(&g_data[0], g_data.size(), 0, false);
 
     for (unsigned n(0); n < g_nsizes.size(); ++n) {
         EXPECT_TRUE(reader.read(nal, size));
         EXPECT_EQ(size, g_nsizes[n]);
         for (int32_t i(0); i < size; ++i)
-            EXPECT_EQ(nal[i], g_data[i+offset]);
-        offset += size;
+            EXPECT_EQ(nal[i], g_data[i + offset + 4]);
```
Comment (xuguangxin) [inline common/nalreader_unittest.cpp]: @uartie ,may have more comments, but I think, 4, 3 are magic number, nobody know what it is could we use same macro for this?

File: common/utils_unittest.cpp [hunk 2]
```diff
@@ -126,9 +126,9 @@ UTILS_TEST(guessResolutionOverflow) {
             << "x"
             << std::numeric_limits<long>::max();
 
-    EXPECT_FALSE(guessResolution(sstream.str().c_str(), w, h));
-    EXPECT_EQ(w, 0);
-    EXPECT_EQ(h, 0);
+    EXPECT_TRUE(guessResolution(sstream.str().c_str(), w, h));
```
Comment (xuguangxin) [inline common/utils_unittest.cpp]: could we make w, h = 0 in this case? Since we will return 0 for "w3840h2160",  better return 0 if we can't get enough room for long.

**Review by xuguangxin — DISMISSED** [review]

File: common/utils_unittest.cpp (hunk 2 above)
Comment (wudping) [reply common/utils_unittest.cpp]: hi @xuguangxin , do you mean that we should assign 0 to width, when it is greater than 3840, so as height ?

File: common/nalreader_unittest.cpp (hunk 1 above)
Comment (wudping) [reply common/nalreader_unittest.cpp]: hi @xuguangxin , @uartie, as you see, 4 is consist of 1 junk byte, and 3 start code bytes.

Comment (uartie) [reply common/nalreader_unittest.cpp]: To make it more clear to reader... keep offset initialization at 1 (i.e. to skip junk byte) and add comment to this effect.  Define a constant start code size = 3.  Then use i + offset + start code size for indexing.  Finally, increment offset by size + start code size.

Add comment to test case about expectation... something like: "For unit reads, the NalReader returns buffer contents between each start code prefix; start code prefix is not included in read result."

File: common/nalreader_unittest.cpp [hunk 3]
```diff
@@ -76,13 +76,13 @@ NALREADER_TEST(ReadAsWhole) {
...
     EXPECT_TRUE(reader.read(nal, size));
-    EXPECT_EQ((size_t)size, g_data.size());
+    EXPECT_EQ((size_t)(size + 4), g_data.size());
 
     for (int32_t i(0); i < size; ++i)
-        EXPECT_EQ(nal[i], g_data[i]);
+        EXPECT_EQ(nal[i], g_data[i + 4]);
 
     EXPECT_FALSE(reader.read(nal, size));
 }
```
Comment (uartie) [inline common/nalreader_unittest.cpp]: Define `const int32_t offset = 4; // 1 initial junk byte + first start code`
Then replace 4's above with `offset`.

Add comment to test case about expectation, for example: "For whole read, the NalReader returns entire buffer contents after first start code.  That is, the first start code prefix is not included in the result."

File: common/utils_unittest.cpp (hunk 2 above)
Comment (uartie) [reply common/utils_unittest.cpp]: This test case should not be changed.  It exposes a bug in `guessResolution`.  Please fix `guessResolution` instead.  That is, `guessResolution` overflows the **int** output parameters (w,h) if it parses a width or height from `filename` param that is larger than what can fit in an `int` value.  This is the bug.

As @xuguangxin pointed out, `guessResolution` should avoid overflow and just make w,h = 0 instead.

**Review by uartie — CHANGES_REQUESTED** [review]

**Comment by wudping** [comment]
Updated according to the detail comments. Thanks.
Please help to review again.

File: common/utils.cpp [hunk 4]
```diff
@@ -121,6 +121,11 @@ bool guessResolution(const char* filename, int& w, int& h)
             sscanf(tokStart, "%d", &h);
         }
     }
+    //"w" or "h" overflows the int, that is dealt with as a bug.
+    if (w < 0 || h < 0) {
```
Comment (uartie) [inline common/utils.cpp]: What happens when you `sscanf` values in the range `long(std::numeric_limits<int>::max()) * 2 + 3`.. `long(std::numeric_limits<int>::max()) * 3 + 2` into an `int`?  This might be worth writing another unittest for.

Perhaps it's better to rewrite this function to use `std::strtol`, validate `errno` afterwards, then verify the result is in the range `0`..`std::numeric_limits<int>::max()` before assigning to w,h.

**Review by uartie — CHANGES_REQUESTED** [review]
Perhaps split the `guessResolution` fixes into a separate pull-request until it's satisfactory.  This way we can merge `nalreader` fixes sooner.

**Comment by wudping** [comment]
okay, @uartie , If guessResultion() pull-request is still with some problem, I will split it into other pull-request.

**Comment by wudping** [comment]
Updated according to detail comments. Thanks @uartie .
Please help to review again, Thanks.

File: common/Makefile.am [hunk 5]
```diff
@@ -30,6 +30,7 @@ libyami_common_ldflags = \
 	$(LIBVA_LIBS) \
 	$(LIBVA_DRM_LIBS) \
 	-lpthread \
+	-std=c++11 \
```
Comment (uartie) [inline common/Makefile.am]: Remove this.  No need for c++11 in this patch series.  I'm pretty sure the libyami project does not approve c++11 yet since some current users may not have it available.

**Review by uartie — CHANGES_REQUESTED** [review]

File: common/Makefile.am (hunk 5 above)
Comment (wudping) [reply common/Makefile.am]: Okay, @uartie.
But as I see it,  std::strtol()  requires c++11. 
If so, I will replace std::strtol with atol().

Comment (uartie) [reply common/Makefile.am]: std::strtol does not requires c++11.  Only std::strtoll does.

http://en.cppreference.com/w/cpp/string/byte/strtol

**Comment by wudping** [comment]
Separated unittest guessResolution() from this patch series. Please help to approve. Thanks.

**Comment by wudping** [comment]
Re-integrate guessResolution() into this patch series, because there are not too many update. Thanks @uartie  for your suggestion.
Please help to review again, Thanks.

**Review by uartie — APPROVED** [review]

**Comment by xuguangxin** [comment]
thansk @uartie for review
